services:
  web:
    container_name: jusicool-web
    image: jusicool-web:latest
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - /home/ubuntu/.env
    network_mode: host
    depends_on:
      - postgres
      - redis

  celery-worker:
    container_name: jusicool-celery-worker
    image: jusicool-celery-worker:latest
    build: .
    command:
      poetry run celery --workdir src -A core.celery worker --loglevel=info
    env_file:
      - /home/ubuntu/.env
    network_mode: host
    depends_on:
      - postgres
      - redis

  celery-beat:
    container_name: jusicool-celery-beat
    image: jusicool-celery-beat:latest
    build: .
    command:
      poetry run celery --workdir src -A core.celery beat --loglevel=info --scheduler celery.beat:Scheduler
    env_file:
      - /home/ubuntu/.env
    network_mode: host
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: jusicool-postgres
    volumes:
      - jusicool-postgres:/var/lib/postgresql/data
    network_mode: host
    env_file:
      - /home/ubuntu/.env

  redis:
    image: redis:7
    container_name: jusicool-redis
    volumes:
      - jusicool-redis:/data
    network_mode: host

  jusicool-grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - jusicool-prometheus
    volumes:
      - jusicool-grafana:/var/lib/grafana
    network_mode: host

  jusicool-prometheus:
    image: prom/prometheus
    network_mode: host

volumes:
  jusicool-postgres:
  jusicool-redis:
  jusicool-grafana: