name: Prod CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          port: ${{ secrets.PROD_SSH_PORT }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/prod/Jusicool-Server
            cd /home/ubuntu/prod/Jusicool-Server
            
            if [ ! -d ".git" ]; then
              git clone -b main https://github.com/Jusicool-Ver-2-0/Jusicool-Server .
            else
              git fetch origin main
              git reset --hard origin/main
            fi
            
            docker-compose down web celery-worker celery-beat || true
                        
            docker-compose up -d --build web celery-worker celery-beat

            docker system prune -f