name: Stage CD

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGE_SSH_HOST }}
          port: ${{ secrets.STAGE_SSH_PORT }}
          username: ${{ secrets.STAGE_SSH_USERNAME }}
          password: ${{ secrets.STAGE_SSH_PASSWORD }}
          script: |
            set -e
            
            docker system prune -f
            
            mkdir -p /home/ubuntu/stage/Jusicool-Server
            cd /home/ubuntu/stage/Jusicool-Server
            
            if [ ! -d ".git" ]; then
              git clone -b develop https://github.com/Jusicool-Ver-2-0/Jusicool-Server .
            else
              git fetch origin develop
              git reset --hard origin/develop
            fi
            
            docker-compose down web celery-worker celery-beat || true
                        
            docker-compose up -d --build web celery-worker celery-beat

            docker system prune -f